version: '3.9'

services:
  frontend:
    image: ${DOCKER_REPOSITORY}/template/frontend/carshop
    #healthcheck:
    #  test: busybox wget -qO - http://localhost/health | grep "UP" || exit 1
    #  interval: 5s
    #  timeout: 5s
    #  retries: 5
    networks:
      - frontend
    ports:
      - 4201:80

networks:
  frontend:
    name: frontend