pipelines:
  default:
      - step:
          name: build
          image: maven:3.8.4-jdk-11
          caches: 
            - maven
          artifacts:
            - "build/**"
          script:
            - mvn clean install -DskipTests
            - mvn clean package verify -DskipTests
            - mkdir build
            - cp ./discoveryserver/target/discoveryserver.jar build/
            - cp ./spring-gateway/target/gateway.jar build/
            - cp ./carShop/target/carShop.jar build/
            - cp ./user/target/user.jar build/
      - step:
          image: docker/compose
          name: Build and dockerize
          services:
            - docker
          script:
            - docker-compose build
            - docker login $DOCKER_REPOSITORY -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            - docker push $DOCKER_REPOSITORY/formazione/carshop/ds
            - docker push $DOCKER_REPOSITORY/formazione/carshop/gateway
            - docker push $DOCKER_REPOSITORY/formazione/carshop/micro1
            - docker push $DOCKER_REPOSITORY/formazione/carshop/micro2
      - step:
          image: atlassian/default-image:3
          name: deploy
          deployment: test
          services:
            - docker
          script:
            - docker login $DOCKER_REPOSITORY -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            - docker-compose -H ssh://$REMOTE_SERVER pull
            - docker-compose -H ssh://$REMOTE_SERVER -p "carshop" up -d --no-build
            
definitions:
  services:
    docker:
      memory: 2048

